// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

namespace Persistence.Migrations.MsuNews
{
    [DbContext(typeof(MsuNewsContext))]
    [Migration("20210407192912_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entitties.News.Draft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReadyForReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Domain.Entitties.News.Publication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Domain.Entitties.News.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DraftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EditedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditetTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newPreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entitties.News.Publication", b =>
                {
                    b.HasOne("Domain.Entitties.News.Review", "EditedArticle")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.Navigation("EditedArticle");
                });

            modelBuilder.Entity("Domain.Entitties.News.Review", b =>
                {
                    b.HasOne("Domain.Entitties.News.Draft", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId");

                    b.Navigation("Draft");
                });
#pragma warning restore 612, 618
        }
    }
}
